version: "3"

services:
  kafka:
    image: spotify/kafka
    ports:
    - "2181:2181"
    - "9092:9092"
    - "8000:8000"
    hostname: kafka
    container_name: kafka
    environment:
    - "ADVERTISED_HOST=kafka"
    - "ADVERTISED_PORT=9092"
    - "AUTO_CREATE_TOPICS=true"

  employee_service_db:
    container_name: employee-service-db
    image: postgres:alpine
    ports:
    - "8432:5432"
    environment:
    - "POSTGRES_USER=employeeservice"
    - "POSTGRES_PASSWORD=employeeservice"
    - "POSTGRES_DB=employeeservice"

  event_service_db:
    container_name: event-service-db
    image: postgres:alpine
    ports:
    - "7432:5432"
    environment:
    - "POSTGRES_USER=eventservice"
    - "POSTGRES_PASSWORD=eventservice"
    - "POSTGRES_DB=eventservice"

#  event_service:
#    container_name: event-service
#    build:
#      context: ./event_service
#      dockerfile: dockerfile

#  employee_service:
#    container_name: employee-service
#    build:
#      context: ./employee_service
#      dockerfile: dockerfile