spring:
  profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:8432/employeeservice
    username: employeeservice
    password: employeeservice
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    producer:
      client-id: employeeservice



server:
  port: 8080


takeaway:
  kafka:
    topic: codechallenge