spring:
  profile: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:7432/eventservice
    username: eventservice
    password: eventservice
    platform: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show_sql: true
    properties:
      hibernate:
        jdbc.time_zone: UTC
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      client-id: eventservice
      group-id: eventservice
      auto-offset-reset: earliest

server:
  port: 8085

takeaway:
  kafka:
    topic: codechallenge